### ISSUE TITLE
[ISSUE] removing integration doesn't remove everything

### ISSUE THREAD

**Issue by dnikles** [raman325/lock_code_manager#443]
### What happened?

I removed lock code manager but if I listen to event call_service and refresh my dashboard, this shows up
```
event_type: call_service
data:
  domain: system_log
  service: write
  service_data:
    logger: frontend.js.modern.202410024
    message: >-
      Unhandled promise rejection from Safari 18.0.1 on Mac OS 10.15.7

      "http://homeassistant.local:8123/lock_code_manager_files/lock-code-manager-strategy.js"
    level: debug
```
Do you know how I can clean this up? I installed through HACS and removed through HACS

### Steps to reproduce the issue

1. Install lock code manager
2. Remove lock code manager

### Home Assistant Version

2024.10.x

### What version of Lock Code Manager are you running?

.5.1
