### ISSUE TITLE
ISSUE: lock_code_manager.hard_refresh_usercodes fails

### ISSUE THREAD

**Issue by tykeal** [raman325/lock_code_manager#46]
**Describe the bug**
I was testing to see what service calls were available and found the **lock_code_maanger.hard_refresh_usercodes** service. I configured it to target the device as well as the entity (tried twice, once with each option set solely). When calling the service I get back the following errors

For setting the target device
> Failed to call service lock_code_manager.hard_refresh_usercodes. extra keys not allowed @ data['device_id']. Got None required key not provided @ data['entity_id']. Got None

The UI generated YAML was

```yaml
service: lock_code_manager.hard_refresh_usercodes
data: {}
target:
  device_id: 96d32f0ab90ff3647a9138bd8af9faa5
```

For setting the target entity
> Failed to call service lock_code_manager.hard_refresh_usercodes. value should be a string for dictionary value @ data['entity_id']. Got None

The UI generated YAML was

```yaml
service: lock_code_manager.hard_refresh_usercodes
data: {}
target:
  entity_id: lock.test_lock
```

**NOTE:** If I modify the YAML to be the following:
```yaml
service: lock_code_manager.hard_refresh_usercodes
data:
  entity_id: lock.test_lock
```

I get no errors, I also don't seem to get feedback if it worked. This tells me that something in your service definition does not seem to be configured correctly for the UI to properly build the service YAML

**Environment (please complete the following information):**

-   OS: HAOS
-   Type of system that HA is running on: KVM
-   Home Assistant version: 2024.2.5
-   Hassio/Docker/Core? HassIO
-   Component version: 0.2.5
-   Lock integration name: ZWave-JS UI
-   Lock make and model: Kwikset 910
