### ISSUE TITLE
[ISSUE] Getting Errors in UI

### ISSUE THREAD

**Issue by rgerrans** [raman325/lock_code_manager#526]
### What happened?

I used to have the integration installed and recently tried to reinstall it.  The device looks fine in Integrations, but when I try to put in place a dashboard with the basic UI I either get a can't find entity_id error or "ERROR: No Lock Code Manager configuration with ID XXXXXX found!" I have verified that is the correct ID

### Steps to reproduce the issue

1.
2.
3.
...

### Home Assistant Version

2025.03.3

### What version of Lock Code Manager are you running?

0.5.1

### Relevant log output

```shell

```

**Comment by markstubb** [comment]
same, using the example from the wiki:
```
Error loading the view strategy:

TypeError: Cannot read properties of undefined (reading 'entity_id')
```

**Comment by alexturpin** [comment]
Same here, getting

> TypeError: Cannot read properties of undefined (reading 'entity_id')

With

```
views:
  - title: Lock Code Manager
    icon: mdi:lock-smart
    strategy:
      type: custom:lock-code-manager
      include_code_slot_sensors: true
      config_entry_title: House Locks
```
