### ISSUE TITLE
[ISSUE] Dashboard error:

### ISSUE THREAD

**Issue by trickford** [raman325/lock_code_manager#527]
### What happened?

When attempting to setup a UI, following [these instructions](https://github.com/raman325/lock_code_manager/wiki/Add-a-UI-for-lock-code-management), I get the following error:

```
Error loading the view strategy:

TypeError: Cannot read properties of undefined (reading 'entity_id')
```

Here is my dashboard yaml config:
```
views:
  - strategy:
      type: custom:lock-code-manager
      config_entry_title: LOCKTEST
      include_code_slot_sensors: false
    icon: mdi:lock-smart
    title: Lock Code Manager
```

Screenshot:
<img width="1606" alt="Image" src="https://github.com/user-attachments/assets/ff722ff6-4a5b-435f-a186-a39bfc4e9a99" />

I can't find any logs for this error, so its' hard to figure out what's going on. If I set lock codes using Lock Code Manager in the Settings > Devices view, it works. Let me know what more information I can provide!

### Steps to reproduce the issue

1. 
2.
3.
...

### Home Assistant Version

2025.5.3

### What version of Lock Code Manager are you running?

0.5.1

### Relevant log output

```shell

```
