### ISSUE TITLE
Version 0.4.0 broke the UI 

### ISSUE THREAD

**Issue by pdobrien3** [raman325/lock_code_manager#86]
### What happened?

ERROR: No Lock Code Manager configuration with ID [redacted] found!

### Steps to reproduce the issue

1. install 0.4.0
2.
3.
...

### Home Assistant Version

2024.3.1

### What version of Lock Code Manager are you running?

0.4.0

### Lock make and model

Kwikset 916 zwave

### Anything else?

Yaml:

```
strategy:
  type: custom:lock-code-manager
  include_code_slot_sensors: true
  
views:
  - strategy:
      type: custom:lock-code-manager
      config_entry_title: Home Locks
      include_code_slot_sensors: true
    icon: mdi:lock-smart
    title: Lock Code Manager
```
